### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by petdance** [amandaleee/developer-interview-questions#6]
- Tell me about a project that didn't go well.
- How do you 
- What challenges does the department/company face in the next month/six months/year?
- How are performance reviews / salary reviews handled?
- What in my background (or on my resume) do you see as the most beneficial for the team?
- What's the work environment like?  Cube farm?  Big open war room?  Can I see (and hear) where I'd be doing my work?
- Are there options for working from home, even partially?
- What do people typically do for lunch?
- Which departments do you typically interface with the most?
- Are projects usually by team or solo?

**Comment by amandaleee** [comment]
These are awesome suggestions! I fixed this in my most recent PR here: https://github.com/amandaleee/developer-interview-questions/pull/7

Thank you! 👍
